# name: README build

# on:
#   push:
#     branches:
#       - master
#   schedule:
#     - cron: '0 */6 * * *'

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout current repository to Master branch
#         uses: actions/checkout@v1
#       - name: Setup NodeJs 13.x
#         uses: actions/setup-python@v1
#         with:
#           python-version: 3.9
#       - uses: actions/cache@v1
#         with:
#           path: ~/.cache/pip
#           key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
#           restore-keys: |
#             ${{runner.os}}-pip-
#       - name: Install dependencies
#         run: python -m pip install -r requirements.txt

#       - name: Generate README file
#         env:
#           SECRET_TOKEN: ${{secrets.TOKEN}}
#         run: |-
#           python make.py
#           cat README.md
      
#       - name: Commit and push (if changed)
#         run: |-
#           git diff
#           git config --global user.email "actions@users.noreply.github.com"
#           git config --global user.name "README-bot"
#           git add  .
#           git commit -m "Refresh readme" || exit 0
#           git push
